### ISSUE TITLE
Schedule listing

### ISSUE THREAD

**Issue by djsanabriac** [AyundandoAyudar/front#47]
En la lista de agendamiento sólo aparecerán los medicamentos que estén en el rango, si el paciente tiene más medicamentos asignados que no entran en el rango de vencimiento estos no será visibles

La agrupación de la lista de agentamiento será por:
Fecha de cumplimiento del periodo
paciente

**Comment by JuanSeBestia** [comment]
Me preguntaba si ya hay un modelo de datos respectivo

**Comment by JuanSeBestia** [comment]
Cerrada por duplicada #50
