### ISSUE TITLE
Patients Service

### ISSUE THREAD

**Issue by KaterineMoon** [AyundandoAyudar/front#9]
This service must manage all the things related with the patients:

- Massive load of medical histories
- CRUD for the patient

*Do not forget to apply the validators in the information upload

**Comment by djsanabriac** [comment]
Close this issue due to is resolved as follows:

    Massive load of medical histories -> #18 
    CRUD for the patient -> #6  (Operations on Firebase service splitted accross different services)

**Comment by KaterineMoon** [comment]
Massive load is in issue #18
